apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghhteew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghhteew
  template:
    metadata:
      labels:
        app: ghhteew
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: ghhteew
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "672fef9c-5445-4d82-9bb6-82261a09cd10"
        - name: Vless_Path
          value: "/vl5thy75u75"
        - name: Vmess_UUID
          value: "672fef9c-5445-4d82-9bb6-82261a09cd10"
        - name: Vmess_Path
          value: "/vmdf73f676"
        - name: Share_Path
          value: "/v2link"
